# Generated by Django 5.0.3 on 2024-04-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='process_data',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('organizatin_name', models.CharField(blank=True, max_length=300, null=True)),
                ('domain', models.CharField(blank=True, max_length=300, null=True)),
                ('year_founded', models.IntegerField(blank=True, max_length=5, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=300, null=True)),
                ('size_range', models.IntegerField(blank=True, max_length=300, null=True)),
                ('locality', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('linkdin_url', models.URLField(blank=True, max_length=300, null=True)),
                ('current_employee_estimate', models.IntegerField(blank=True, max_length=300, null=True)),
                ('total_employee_estimate', models.IntegerField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
