# Generated by Django 5.0.3 on 2024-04-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0002_alter_process_data_current_employee_estimate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process_data',
            old_name='linkdin_url',
            new_name='link_url',
        ),
        migrations.RenameField(
            model_name='process_data',
            old_name='organizatin_name',
            new_name='organization_name',
        ),
    ]
