# Generated by Django 5.0.3 on 2024-04-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0003_rename_linkdin_url_process_data_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_data',
            name='size_range',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
